- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.0
  hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: debug-statements
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: flake8
    args: [--max-line-length=120]
    exclude: migrations
  - id: name-tests-test
    args: [--django]
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: git://github.com/chewse/pre-commit-mirrors-pydocstyle
  sha: v2.1.1
  hooks:
  - id: pydocstyle
    exclude: migrations
